@BASE_URL=http://localhost:3000

### get all posts
GET {{BASE_URL}}/post/all

### add new post 
POST {{BASE_URL}}/post HTTP/1.1
Content-Type: application/json

{
"post": {
    "id": 6488,
    "senderId": 155,
    "content": "hello world",
    "comments": [{
        "id": 1,
        "senderId": 8,
        "content": "comment"
        },
        {
        "id": 2,
        "senderId": 9,
        "content": "comment 2"
        }
        ]
    }
}

### get post by postID 
GET {{BASE_URL}}/post/6488

### get posts by userID  
GET {{BASE_URL}}/post?sender=15

### change content for given postID 
PUT {{BASE_URL}}/post/12345
Content-Type: application/json

{
"content": "new content cool!!!"
}

### get all comments for post id
GET {{BASE_URL}}/comment/123456


### Create a Comment for post id
POST {{BASE_URL}}/comment/6488
Content-Type: application/json

{
 "comment": {
    "id": 3,
    "senderId": 10025,
    "content": "This is a comment on the post!!"
    }
}

### Update a Comment in post
PUT {{BASE_URL}}/comment/6488/2
Content-Type: application/json

{
 "content": "new content- after update the comment"
}

### find specific comment id in post id
GET {{BASE_URL}}/comment/1234/1
Content-Type: application/json

### delete a comment from post
DELETE {{BASE_URL}}/comment/6488/3
Content-Type: application/json

### USERS API

### get all users
GET {{BASE_URL}}/user/all

### get user by userID
GET {{BASE_URL}}/user/1

### add new user
POST {{BASE_URL}}/user HTTP/1.1
Content-Type: application/json

{
"user": {
    "id": 10025,
    "username": "israel-israeli",
    "email": "israel@gmail.com",
    "password": "Israel123!!!"
    }
}

### delete user by userID
DELETE {{BASE_URL}}/user/10025

### update user by userID
PUT {{BASE_URL}}/user/1 HTTP/1.1
Content-Type: application/json

{
  "username": "new-username",
  "password": "NewPassword123!!!"
}